name: Test Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Time
        run: |
          echo "Workflow started"
          date
